# Generated by Django 4.1 on 2023-02-28 17:56

from django.db import migrations, models
import django.db.models.deletion
import project.mixin


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceModification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="names of this object in the form of a dictionnary, i.e. {'fr':'Nom', 'en':'Name'}",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "ratio",
                    models.FloatField(help_text="ratio to apply to the linked source"),
                ),
                (
                    "emission_factor",
                    models.FloatField(
                        help_text="emission of the source in Source Unit/kgCO2e"
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sourceModifications",
                        to="tapio.source",
                    ),
                ),
            ],
            bases=(project.mixin.ModelSignals, models.Model),
        ),
    ]
