# Generated by Django 4.1 on 2023-03-01 10:45

from django.db import migrations, models
import django.db.models.deletion
import project.mixin


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0002_sourcemodification"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ratio",
                    models.FloatField(help_text="ratio to apply to the linked source"),
                ),
            ],
            bases=(project.mixin.ModelSignals, models.Model),
        ),
        migrations.RenameField(
            model_name="source",
            old_name="lifetime",
            new_name="lifetime_local",
        ),
        migrations.RemoveField(
            model_name="source",
            name="emission_factor",
        ),
        migrations.RemoveField(
            model_name="source",
            name="total_emission",
        ),
        migrations.RemoveField(
            model_name="source",
            name="value",
        ),
        migrations.AddField(
            model_name="source",
            name="children",
            field=models.ManyToManyField(
                help_text="List of direct source children",
                related_name="parents",
                through="tapio.SourceLink",
                to="tapio.source",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="emission_factor_computed",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="emission of the source in Unit/kgCO2e",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="emission_factor_local",
            field=models.FloatField(
                blank=True, help_text="emission of the source in Unit/kgCO2e", null=True
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="lifetime_computed",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="total_emission_computed",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="Total emission in kgCO2e",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[("S", "source"), ("MS", "modifcation")],
                db_index=True,
                default="S",
                help_text="type of this source: original source (S) or modified source (MS)",
                max_length=256,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="value_computed",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="quantity of source in Unit",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="value_local",
            field=models.FloatField(
                blank=True, help_text="quantity of source in Unit", null=True
            ),
        ),
        migrations.DeleteModel(
            name="SourceModification",
        ),
        migrations.AddField(
            model_name="sourcelink",
            name="child",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sourceModification",
                to="tapio.source",
            ),
        ),
        migrations.AddField(
            model_name="sourcelink",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="tapio.source",
            ),
        ),
    ]
