# Generated by Django 4.1 on 2023-03-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0003_sourcelink_rename_lifetime_source_lifetime_local_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcelink",
            name="ratio",
            field=models.FloatField(
                blank=True, default=1, help_text="ratio to apply to the linked source"
            ),
        ),
    ]
