# Generated by Django 4.1 on 2023-03-01 13:08

from django.db import migrations, models
import django.db.models.deletion
import project.mixin


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0004_alter_sourcelink_ratio"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModifiedSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "names",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="names of this object in the form of a dictionnary, i.e. {'fr':'Nom', 'en':'Name'}",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "ratio",
                    models.FloatField(
                        blank=True,
                        default=1,
                        help_text="Ratio to apply to the original source",
                    ),
                ),
                (
                    "emission_factor",
                    models.FloatField(
                        blank=True,
                        help_text="local emission of the modified source (if different than origianl) in Unit/kgCO2e",
                        null=True,
                    ),
                ),
                (
                    "total_emission",
                    models.FloatField(
                        blank=True,
                        editable=False,
                        help_text="Total emission in kgCO2e",
                        null=True,
                    ),
                ),
                (
                    "acquisition_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            bases=(project.mixin.ModelSignals, models.Model),
        ),
        migrations.RenameField(
            model_name="source",
            old_name="emission_factor_local",
            new_name="emission_factor",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="lifetime_local",
            new_name="lifetime",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="total_emission_computed",
            new_name="total_emission",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="value_local",
            new_name="value",
        ),
        migrations.RemoveField(
            model_name="source",
            name="children",
        ),
        migrations.RemoveField(
            model_name="source",
            name="emission_factor_computed",
        ),
        migrations.RemoveField(
            model_name="source",
            name="lifetime_computed",
        ),
        migrations.RemoveField(
            model_name="source",
            name="report",
        ),
        migrations.RemoveField(
            model_name="source",
            name="type",
        ),
        migrations.RemoveField(
            model_name="source",
            name="value_computed",
        ),
        migrations.AddField(
            model_name="report",
            name="sources",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="tapio.source",
            ),
        ),
        migrations.DeleteModel(
            name="SourceLink",
        ),
        migrations.AddField(
            model_name="modifiedsource",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modifiedSources",
                to="tapio.source",
            ),
        ),
    ]
