# Generated by Django 4.1 on 2023-03-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0006_remove_report_sources_report_sources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="sources",
            field=models.ManyToManyField(
                blank=True, related_name="reports", to="tapio.source"
            ),
        ),
    ]
