# Generated by Django 4.1 on 2023-03-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0007_alter_report_sources"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="scenarios",
            field=models.JSONField(
                default=list,
                help_text="list of modified sources per scenario {scenario_1 : [{'s_id1' : 'ms_id1'}, ..], scenario_2 : [{'s_id1' : 'ms_id2'}, ..]}",
            ),
        ),
    ]
