# Generated by Django 4.1 on 2023-03-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tapio", "0009_alter_report_scenarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, help_text="Carbon footprint report year", null=True
            ),
        ),
    ]
